### ISSUE TITLE
Adds invalid "includePath" properties into exported OpenAPI 3.0 types when modular RAML is used

### ISSUE THREAD

**Issue by Windowsfreak** [daviemakz/oas-raml-converter-cli#24]
When using !include statements for better RAML modularisation, e.g.

```yaml
#main.raml

types:
  Response: !include types/myResponse.raml
```

```yaml
#types/myResponse.raml

#%RAML 1.0 DataType
properties:
  // ...
```

Then the generated specification will contain an extra property `includePath` in the types that does not belong to OpenAPI 3.0 specification:
```json
{ // ...
      "Response": {
        "includePath": "types/myResponse.raml", // ...
      }
}
```
